<?php
class research_model extends CI_Model
{
    public function mental_health($date)
    {
        $this->db->select("
          SUM(follow_up) AS follow_up_total,
          SUM(higher_level) AS higher_level_total,
          SUM(hospitalized) AS hospitalized_total,
          SUM(anxiety_nc19m) AS anxiety_nc19m_total,
          SUM(anxiety_nc19f) AS anxiety_nc19f_total,
          SUM(anxiety_nc39m) AS anxiety_nc39m_total,
          SUM(anxiety_nc39f) AS anxiety_nc39f_total,
          SUM(anxiety_nc40m) AS anxiety_nc40m_total,
          SUM(anxiety_nc40f) AS anxiety_nc40f_total,
          SUM(stress_nc19m) AS stress_nc19m_total,
          SUM(stress_nc19f) AS stress_nc19f_total,
          SUM(stress_nc39m) AS stress_nc39m_total,
          SUM(stress_nc39f) AS stress_nc39f_total,
          SUM(stress_nc40m) AS stress_nc40m_total,
          SUM(stress_nc40f) AS stress_nc40f_total,
          SUM(schizo_nc19m) AS schizo_nc19m_total,
          SUM(schizo_nc19f) AS schizo_nc19f_total,
          SUM(schizo_nc39m) AS schizo_nc39m_total,
          SUM(schizo_nc39f) AS schizo_nc39f_total,
          SUM(schizo_nc40m) AS schizo_nc40m_total,
          SUM(schizo_nc40f) AS schizo_nc40f_total,
          SUM(soma_nc19m) AS soma_nc19m_total,
          SUM(soma_nc19f) AS soma_nc19f_total,
          SUM(soma_nc39m) AS soma_nc39m_total,
          SUM(soma_nc39f) AS soma_nc39f_total,
          SUM(soma_nc40m) AS soma_nc40m_total,
          SUM(soma_nc40f) AS soma_nc40f_total,
          SUM(child_nc19m) AS child_nc19m_total,
          SUM(child_nc19f) AS child_nc19f_total,
          SUM(child_nc39m) AS child_nc39m_total,
          SUM(child_nc39f) AS child_nc39f_total,
          SUM(child_nc40m) AS child_nc40m_total,
          SUM(child_nc40f) AS child_nc40f_total,
          SUM(alcohol_nc19m) AS alcohol_nc19m_total,
          SUM(alcohol_nc19f) AS alcohol_nc19f_total,
          SUM(alcohol_nc39m) AS alcohol_nc39m_total,
          SUM(alcohol_nc39f) AS alcohol_nc39f_total,
          SUM(alcohol_nc40m) AS alcohol_nc40m_total,
          SUM(alcohol_nc40f) AS alcohol_nc40f_total,
          SUM(drugs_nc19m) AS drugs_nc19m_total,
          SUM(drugs_nc19f) AS drugs_nc19f_total,
          SUM(drugs_nc39m) AS drugs_nc39m_total,
          SUM(drugs_nc39f) AS drugs_nc39f_total,
          SUM(drugs_nc40m) AS drugs_nc40m_total,
          SUM(drugs_nc40f) AS drugs_nc40f_total,
          SUM(dep_nc19m) AS dep_nc19m_total,
          SUM(dep_nc19f) AS dep_nc19f_total,
          SUM(dep_nc39m) AS dep_nc39m_total,
          SUM(dep_nc39f) AS dep_nc39f_total,
          SUM(dep_nc40m) AS dep_nc40m_total,
          SUM(dep_nc40f) AS dep_nc40f_total,
          SUM(suicid_att_nc19m) AS suicid_att_nc19m_total,
          SUM(suicid_att_nc19f) AS suicid_att_nc19f_total,
          SUM(suicid_att_nc39m) AS suicid_att_nc39m_total,
          SUM(suicid_att_nc39f) AS suicid_att_nc39f_total,
          SUM(suicid_att_nc40m) AS suicid_att_nc40m_total,
          SUM(suicid_att_nc40f) AS suicid_att_nc40f_total,
          SUM(suicid_d_nc19m) AS suicid_d_nc19m_total,
          SUM(suicid_d_nc19f) AS suicid_d_nc19f_total,
          SUM(suicid_d_nc39m) AS suicid_d_nc39m_total,
          SUM(suicid_d_nc39f) AS suicid_d_nc39f_total,
          SUM(suicid_d_nc40m) AS suicid_d_nc40m_total,
          SUM(suicid_d_nc40f) AS suicid_d_nc40f_total,
          SUM(maniac_nc19m) AS maniac_nc19m_total,
          SUM(maniac_nc19f) AS maniac_nc19f_total,
          SUM(maniac_nc39m) AS maniac_nc39m_total,
          SUM(maniac_nc39f) AS maniac_nc39f_total,
          SUM(maniac_nc40m) AS maniac_nc40m_total,
          SUM(maniac_nc40f) AS maniac_nc40f_total,
          SUM(bipolar_nc19m) AS bipolar_nc19m_total,
          SUM(bipolar_nc19f) AS bipolar_nc19f_total,
          SUM(bipolar_nc39m) AS bipolar_nc39m_total,
          SUM(bipolar_nc39f) AS bipolar_nc39f_total,
          SUM(bipolar_nc40m) AS bipolar_nc40m_total,
          SUM(bipolar_nc40f) AS bipolar_nc40f_total,
          SUM(other_psy_nc19m) AS other_psy_nc19m_total,
          SUM(other_psy_nc19f) AS other_psy_nc19f_total,
          SUM(other_psy_nc39m) AS other_psy_nc39m_total,
          SUM(other_psy_nc39f) AS other_psy_nc39f_total,
          SUM(other_psy_nc40m) AS other_psy_nc40m_total,
          SUM(other_psy_nc40f) AS other_psy_nc40f_total,
          SUM(epilepsy_nc19m) AS epilepsy_nc19m_total,
          SUM(epilepsy_nc19f) AS epilepsy_nc19f_total,
          SUM(epilepsy_nc39m) AS epilepsy_nc39m_total,
          SUM(epilepsy_nc39f) AS epilepsy_nc39f_total,
          SUM(epilepsy_nc40m) AS epilepsy_nc40m_total,
          SUM(epilepsy_nc40f) AS epilepsy_nc40f_total,
          SUM(other_neuro_nc19m) AS other_neuro_nc19m_total,
          SUM(other_neuro_nc19f) AS other_neuro_nc19f_total,
          SUM(other_neuro_nc39m) AS other_neuro_nc39m_total,
          SUM(other_neuro_nc39f) AS other_neuro_nc39f_total,
          SUM(other_neuro_nc40m) AS other_neuro_nc40m_total,
          SUM(other_neuro_nc40f) AS other_neuro_nc40f_total,
          SUM(anxiety_oc19m) AS anxiety_oc19m_total,
          SUM(anxiety_oc19f) AS anxiety_oc19f_total,
          SUM(anxiety_oc39m) AS anxiety_oc39m_total,
          SUM(anxiety_oc39f) AS anxiety_oc39f_total,
          SUM(anxiety_oc40m) AS anxiety_oc40m_total,
          SUM(anxiety_oc40f) AS anxiety_oc40f_total,
          SUM(stress_oc19m) AS stress_oc19m_total,
          SUM(stress_oc19f) AS stress_oc19f_total,
          SUM(stress_oc39m) AS stress_oc39m_total,
          SUM(stress_oc39f) AS stress_oc39f_total,
          SUM(stress_oc40m) AS stress_oc40m_total,
          SUM(stress_oc40f) AS stress_oc40f_total,
          SUM(schizo_oc19m) AS schizo_oc19m_total,
          SUM(schizo_oc19f) AS schizo_oc19f_total,
          SUM(schizo_oc39m) AS schizo_oc39m_total,
          SUM(schizo_oc39f) AS schizo_oc39f_total,
          SUM(schizo_oc40m) AS schizo_oc40m_total,
          SUM(schizo_oc40f) AS schizo_oc40f_total,
          SUM(soma_oc19m) AS soma_oc19m_total,
          SUM(soma_oc19f) AS soma_oc19f_total,
          SUM(soma_oc39m) AS soma_oc39m_total,
          SUM(soma_oc39f) AS soma_oc39f_total,
          SUM(soma_oc40m) AS soma_oc40m_total,
          SUM(soma_oc40f) AS soma_oc40f_total,
          SUM(child_oc19m) AS child_oc19m_total,
          SUM(child_oc19f) AS child_oc19f_total,
          SUM(child_oc39m) AS child_oc39m_total,
          SUM(child_oc39f) AS child_oc39f_total,
          SUM(child_oc40m) AS child_oc40m_total,
          SUM(child_oc40f) AS child_oc40f_total,
          SUM(alcohol_oc19m) AS alcohol_oc19m_total,
          SUM(alcohol_oc19f) AS alcohol_oc19f_total,
          SUM(alcohol_oc39m) AS alcohol_oc39m_total,
          SUM(alcohol_oc39f) AS alcohol_oc39f_total,
          SUM(alcohol_oc40m) AS alcohol_oc40m_total,
          SUM(alcohol_oc40f) AS alcohol_oc40f_total,
          SUM(drugs_oc19m) AS drugs_oc19m_total,
          SUM(drugs_oc19f) AS drugs_oc19f_total,
          SUM(drugs_oc39m) AS drugs_oc39m_total,
          SUM(drugs_oc39f) AS drugs_oc39f_total,
          SUM(drugs_oc40m) AS drugs_oc40m_total,
          SUM(drugs_oc40f) AS drugs_oc40f_total,
          SUM(dep_oc19m) AS dep_oc19m_total,
          SUM(dep_oc19f) AS dep_oc19f_total,
          SUM(dep_oc39m) AS dep_oc39m_total,
          SUM(dep_oc39f) AS dep_oc39f_total,
          SUM(dep_oc40m) AS dep_oc40m_total,
          SUM(dep_oc40f) AS dep_oc40f_total,
          SUM(suicid_att_oc19m) AS suicid_att_oc19m_total,
          SUM(suicid_att_oc19f) AS suicid_att_oc19f_total,
          SUM(suicid_att_oc39m) AS suicid_att_oc39m_total,
          SUM(suicid_att_oc39f) AS suicid_att_oc39f_total,
          SUM(suicid_att_oc40m) AS suicid_att_oc40m_total,
          SUM(suicid_att_oc40f) AS suicid_att_oc40f_total,
          SUM(suicid_d_oc19m) AS suicid_d_oc19m_total,
          SUM(suicid_d_oc19f) AS suicid_d_oc19f_total,
          SUM(suicid_d_oc39m) AS suicid_d_oc39m_total,
          SUM(suicid_d_oc39f) AS suicid_d_oc39f_total,
          SUM(suicid_d_oc40m) AS suicid_d_oc40m_total,
          SUM(suicid_d_oc40f) AS suicid_d_oc40f_total,
          SUM(maniac_oc19m) AS maniac_oc19m_total,
          SUM(maniac_oc19f) AS maniac_oc19f_total,
          SUM(maniac_oc39m) AS maniac_oc39m_total,
          SUM(maniac_oc39f) AS maniac_oc39f_total,
          SUM(maniac_oc40m) AS maniac_oc40m_total,
          SUM(maniac_oc40f) AS maniac_oc40f_total,
          SUM(bipolar_oc19m) AS bipolar_oc19m_total,
          SUM(bipolar_oc19f) AS bipolar_oc19f_total,
          SUM(bipolar_oc39m) AS bipolar_oc39m_total,
          SUM(bipolar_oc39f) AS bipolar_oc39f_total,
          SUM(bipolar_oc40m) AS bipolar_oc40m_total,
          SUM(bipolar_oc40f) AS bipolar_oc40f_total,
          SUM(other_psy_oc19m) AS other_psy_oc19m_total,
          SUM(other_psy_oc19f) AS other_psy_oc19f_total,
          SUM(other_psy_oc39m) AS other_psy_oc39m_total,
          SUM(other_psy_oc39f) AS other_psy_oc39f_total,
          SUM(other_psy_oc40m) AS other_psy_oc40m_total,
          SUM(other_psy_oc40f) AS other_psy_oc40f_total,
          SUM(epilepsy_oc19m) AS epilepsy_oc19m_total,
          SUM(epilepsy_oc19f) AS epilepsy_oc19f_total,
          SUM(epilepsy_oc39m) AS epilepsy_oc39m_total,
          SUM(epilepsy_oc39f) AS epilepsy_oc39f_total,
          SUM(epilepsy_oc40m) AS epilepsy_oc40m_total,
          SUM(epilepsy_oc40f) AS epilepsy_oc40f_total,
          SUM(other_neuro_oc19m) AS other_neuro_oc19m_total,
          SUM(other_neuro_oc19f) AS other_neuro_oc19f_total,
          SUM(other_neuro_oc39m) AS other_neuro_oc39m_total,
          SUM(other_neuro_oc39f) AS other_neuro_oc39f_total,
          SUM(other_neuro_oc40m) AS other_neuro_oc40m_total,
          SUM(other_neuro_oc40f) AS other_neuro_oc40f_total,
        ");
        $this->db->from('Mental_Health');
        $this->db->where('date_mental_health', $date);
        return $this->db->get()->row();
    }

    public function other_cardiovascular($date)
    {
        return $this->db->get_where('Other_Cardiovascular', array('date_other_cardiovascular' => $date))->row();
    }

    public function palliative_care($date)
    {
        return $this->db->get_where('Palliative_Care', array('date_palliative_care' => $date))->row();
    }

    public function community_checkup($date)
    {
        return $this->db->get_where('Community_Checkup', array('date_community_checkup' => $date))->row();
    }

    public function cancer_screening($date)
    {
        return $this->db->get_where('Cancer_Screening', array('date_cancer_screening' => $date))->row();
    }

    public function hospitalization_a($date)
    {
        return $this->db->get_where('Hospitalization_A', array('date_hospitalization_a' => $date))->row();
    }

    public function hospitalization_bcde($date)
    {
        $this->db->select("
          SUM(hosp_1m) AS hosp_1m_total,
          SUM(hosp_1f) AS hosp_1f_total,
          SUM(hosp_4m) AS hosp_4m_total,
          SUM(hosp_4f) AS hosp_4f_total,
          SUM(hosp_19m) AS hosp_19m_total,
          SUM(hosp_19f) AS hosp_19f_total,
          SUM(hosp_20m) AS hosp_20m_total,
          SUM(hosp_20f) AS hosp_20f_total,
          SUM(deaths_1m) AS deaths_1m_total,
          SUM(deaths_1f) AS deaths_1f_total,
          SUM(deaths_4m) AS deaths_4m_total,
          SUM(deaths_4f) AS deaths_4f_total,
          SUM(deaths_19m) AS deaths_19m_total,
          SUM(deaths_19f) AS deaths_19f_total,
          SUM(deaths_20m) AS deaths_20m_total,
          SUM(deaths_20f) AS deaths_20f_total,
          SUM(insured_dis) AS insured_dis_total,
          SUM(no_paying_dis) AS no_paying_dis_total,
          SUM(no_paying_ind) AS no_paying_ind_total,
          SUM(road_acc_ad) AS road_acc_ad_total,
          SUM(road_acc_deaths) AS road_acc_deaths_total,
          SUM(natural_disa_ad) AS natural_disa_ad_total,
          SUM(natural_disa_deaths) AS natural_disa_deaths_total,
          SUM(work_inj_ad) AS work_inj_ad_total,
          SUM(work_inj_deaths) AS work_inj_deaths_total,
          SUM(malaria_sim_hos5m) AS malaria_sim_hos5m_total,
          SUM(malaria_sim_hos5f) AS malaria_sim_hos5f_total,
          SUM(malaria_sim_hos19m) AS malaria_sim_hos19m_total,
          SUM(malaria_sim_hos19f) AS malaria_sim_hos19f_total,
          SUM(malaria_sim_hos20m) AS malaria_sim_hos20m_total,
          SUM(malaria_sim_hos20f) AS malaria_sim_hos20f_total,
          SUM(malaria_sev_hos5m) AS malaria_sev_hos5m_total,
          SUM(malaria_sev_hos5f) AS malaria_sev_hos5f_total,
          SUM(malaria_sev_hos19m) AS malaria_sev_hos19m_total,
          SUM(malaria_sev_hos19f) AS malaria_sev_hos19f_total,
          SUM(malaria_sev_hos20m) AS malaria_sev_hos20m_total,
          SUM(malaria_sev_hos20f) AS malaria_sev_hos20f_total,
          SUM(malaria_sev_deaths5m) AS malaria_sev_deaths5m_total,
          SUM(malaria_sev_deaths5f) AS malaria_sev_deaths5f_total,
          SUM(malaria_sev_deaths19m) AS malaria_sev_deaths19m_total,
          SUM(malaria_sev_deaths19f) AS malaria_sev_deaths19f_total,
          SUM(malaria_sev_deaths20m) AS malaria_sev_deaths20m_total,
          SUM(malaria_sev_deaths20f) AS malaria_sev_deaths20f_total,
          SUM(borreliosis_hos5m) AS borreliosis_hos5m_total,
          SUM(borreliosis_hos5f) AS borreliosis_hos5f_total,
          SUM(borreliosis_hos19m) AS borreliosis_hos19m_total,
          SUM(borreliosis_hos19f) AS borreliosis_hos19f_total,
          SUM(borreliosis_hos20m) AS borreliosis_hos20m_total,
          SUM(borreliosis_hos20f) AS borreliosis_hos20f_total,
          SUM(borreliosis_deaths5m) AS borreliosis_deaths5m_total,
          SUM(borreliosis_deaths5f) AS borreliosis_deaths5f_total,
          SUM(borreliosis_deaths19m) AS borreliosis_deaths19m_total,
          SUM(borreliosis_deaths19f) AS borreliosis_deaths19f_total,
          SUM(borreliosis_deaths20m) AS borreliosis_deaths20m_total,
          SUM(borreliosis_deaths20f) AS borreliosis_deaths20f_total,
          SUM(pneumonia_sim_hos5m) AS pneumonia_sim_hos5m_total,
          SUM(pneumonia_sim_hos5f) AS pneumonia_sim_hos5f_total,
          SUM(pneumonia_sim_hos19m) AS pneumonia_sim_hos19m_total,
          SUM(pneumonia_sim_hos19f) AS pneumonia_sim_hos19f_total,
          SUM(pneumonia_sim_hos20m) AS pneumonia_sim_hos20m_total,
          SUM(pneumonia_sim_hos20f) AS pneumonia_sim_hos20f_total,
          SUM(pneumonia_sim_deaths5m) AS pneumonia_sim_deaths5m_total,
          SUM(pneumonia_sim_deaths5f) AS pneumonia_sim_deaths5f_total,
          SUM(pneumonia_sim_deaths19m) AS pneumonia_sim_deaths19m_total,
          SUM(pneumonia_sim_deaths19f) AS pneumonia_sim_deaths19f_total,
          SUM(pneumonia_sim_deaths20m) AS pneumonia_sim_deaths20m_total,
          SUM(pneumonia_sim_deaths20f) AS pneumonia_sim_deaths20f_total,
          SUM(pneumonia_sev_hos5m) AS pneumonia_sev_hos5m_total,
          SUM(pneumonia_sev_hos5f) AS pneumonia_sev_hos5f_total,
          SUM(pneumonia_sev_hos19m) AS pneumonia_sev_hos19m_total,
          SUM(pneumonia_sev_hos19f) AS pneumonia_sev_hos19f_total,
          SUM(pneumonia_sev_hos20m) AS pneumonia_sev_hos20m_total,
          SUM(pneumonia_sev_hos20f) AS pneumonia_sev_hos20f_total,
          SUM(pneumonia_sev_deaths5m) AS pneumonia_sev_deaths5m_total,
          SUM(pneumonia_sev_deaths5f) AS pneumonia_sev_deaths5f_total,
          SUM(pneumonia_sev_deaths19m) AS pneumonia_sev_deaths19m_total,
          SUM(pneumonia_sev_deaths19f) AS pneumonia_sev_deaths19f_total,
          SUM(pneumonia_sev_deaths20m) AS pneumonia_sev_deaths20m_total,
          SUM(pneumonia_sev_deaths20f) AS pneumonia_sev_deaths20f_total,
          SUM(pleurisy_hos5m) AS pleurisy_hos5m_total,
          SUM(pleurisy_hos5f) AS pleurisy_hos5f_total,
          SUM(pleurisy_hos19m) AS pleurisy_hos19m_total,
          SUM(pleurisy_hos19f) AS pleurisy_hos19f_total,
          SUM(pleurisy_hos20m) AS pleurisy_hos20m_total,
          SUM(pleurisy_hos20f) AS pleurisy_hos20f_total,
          SUM(pleurisy_deaths5m) AS pleurisy_deaths5m_total,
          SUM(pleurisy_deaths5f) AS pleurisy_deaths5f_total,
          SUM(pleurisy_deaths19m) AS pleurisy_deaths19m_total,
          SUM(pleurisy_deaths19f) AS pleurisy_deaths19f_total,
          SUM(pleurisy_deaths20m) AS pleurisy_deaths20m_total,
          SUM(pleurisy_deaths20f) AS pleurisy_deaths20f_total,
          SUM(ari_hos5m) AS ari_hos5m_total,
          SUM(ari_hos5f) AS ari_hos5f_total,
          SUM(ari_hos19m) AS ari_hos19m_total,
          SUM(ari_hos19f) AS ari_hos19f_total,
          SUM(ari_hos20m) AS ari_hos20m_total,
          SUM(ari_hos20f) AS ari_hos20f_total,
          SUM(ari_deaths5m) AS ari_deaths5m_total,
          SUM(ari_deaths5f) AS ari_deaths5f_total,
          SUM(ari_deaths19m) AS ari_deaths19m_total,
          SUM(ari_deaths19f) AS ari_deaths19f_total,
          SUM(ari_deaths20m) AS ari_deaths20m_total,
          SUM(ari_deaths20f) AS ari_deaths20f_total,
          SUM(diarr_bloody_hos5m) AS diarr_bloody_hos5m_total,
          SUM(diarr_bloody_hos5f) AS diarr_bloody_hos5f_total,
          SUM(diarr_bloody_hos19m) AS diarr_bloody_hos19m_total,
          SUM(diarr_bloody_hos19f) AS diarr_bloody_hos19f_total,
          SUM(diarr_bloody_hos20m) AS diarr_bloody_hos20m_total,
          SUM(diarr_bloody_hos20f) AS diarr_bloody_hos20f_total,
          SUM(diarr_bloody_deaths5m) AS diarr_bloody_deaths5m_total,
          SUM(diarr_bloody_deaths5f) AS diarr_bloody_deaths5f_total,
          SUM(diarr_bloody_deaths19m) AS diarr_bloody_deaths19m_total,
          SUM(diarr_bloody_deaths19f) AS diarr_bloody_deaths19f_total,
          SUM(diarr_bloody_deaths20m) AS diarr_bloody_deaths20m_total,
          SUM(diarr_bloody_deaths20f) AS diarr_bloody_deaths20f_total,
          SUM(diarr_dehy_hos5m) AS diarr_dehy_hos5m_total,
          SUM(diarr_dehy_hos5f) AS diarr_dehy_hos5f_total,
          SUM(diarr_dehy_hos19m) AS diarr_dehy_hos19m_total,
          SUM(diarr_dehy_hos19f) AS diarr_dehy_hos19f_total,
          SUM(diarr_dehy_hos20m) AS diarr_dehy_hos20m_total,
          SUM(diarr_dehy_hos20f) AS diarr_dehy_hos20f_total,
          SUM(diarr_dehy_deaths5m) AS diarr_dehy_deaths5m_total,
          SUM(diarr_dehy_deaths5f) AS diarr_dehy_deaths5f_total,
          SUM(diarr_dehy_deaths19m) AS diarr_dehy_deaths19m_total,
          SUM(diarr_dehy_deaths19f) AS diarr_dehy_deaths19f_total,
          SUM(diarr_dehy_deaths20m) AS diarr_dehy_deaths20m_total,
          SUM(diarr_dehy_deaths20f) AS diarr_dehy_deaths20f_total,
          SUM(diarr_no_dehy_hos5m) AS diarr_no_dehy_hos5m_total,
          SUM(diarr_no_dehy_hos5f) AS diarr_no_dehy_hos5f_total,
          SUM(diarr_no_dehy_hos19m) AS diarr_no_dehy_hos19m_total,
          SUM(diarr_no_dehy_hos19f) AS diarr_no_dehy_hos19f_total,
          SUM(diarr_no_dehy_hos20m) AS diarr_no_dehy_hos20m_total,
          SUM(diarr_no_dehy_hos20f) AS diarr_no_dehy_hos20f_total,
          SUM(diarr_no_dehy_deaths5m) AS diarr_no_dehy_deaths5m_total,
          SUM(diarr_no_dehy_deaths5f) AS diarr_no_dehy_deaths5f_total,
          SUM(diarr_no_dehy_deaths19m) AS diarr_no_dehy_deaths19m_total,
          SUM(diarr_no_dehy_deaths19f) AS diarr_no_dehy_deaths19f_total,
          SUM(diarr_no_dehy_deaths20m) AS diarr_no_dehy_deaths20m_total,
          SUM(diarr_no_dehy_deaths20f) AS diarr_no_dehy_deaths20f_total,
          SUM(cholera_hos5m) AS cholera_hos5m_total,
          SUM(cholera_hos5f) AS cholera_hos5f_total,
          SUM(cholera_hos19m) AS cholera_hos19m_total,
          SUM(cholera_hos19f) AS cholera_hos19f_total,
          SUM(cholera_hos20m) AS cholera_hos20m_total,
          SUM(cholera_hos20f) AS cholera_hos20f_total,
          SUM(cholera_deaths5m) AS cholera_deaths5m_total,
          SUM(cholera_deaths5f) AS cholera_deaths5f_total,
          SUM(cholera_deaths19m) AS cholera_deaths19m_total,
          SUM(cholera_deaths19f) AS cholera_deaths19f_total,
          SUM(cholera_deaths20m) AS cholera_deaths20m_total,
          SUM(cholera_deaths20f) AS cholera_deaths20f_total,
          SUM(typhoid_hos5m) AS typhoid_hos5m_total,
          SUM(typhoid_hos5f) AS typhoid_hos5f_total,
          SUM(typhoid_hos19m) AS typhoid_hos19m_total,
          SUM(typhoid_hos19f) AS typhoid_hos19f_total,
          SUM(typhoid_hos20m) AS typhoid_hos20m_total,
          SUM(typhoid_hos20f) AS typhoid_hos20f_total,
          SUM(typhoid_deaths5m) AS typhoid_deaths5m_total,
          SUM(typhoid_deaths5f) AS typhoid_deaths5f_total,
          SUM(typhoid_deaths19m) AS typhoid_deaths19m_total,
          SUM(typhoid_deaths19f) AS typhoid_deaths19f_total,
          SUM(typhoid_deaths20m) AS typhoid_deaths20m_total,
          SUM(typhoid_deaths20f) AS typhoid_deaths20f_total,
          SUM(meningitis_hos5m) AS meningitis_hos5m_total,
          SUM(meningitis_hos5f) AS meningitis_hos5f_total,
          SUM(meningitis_hos19m) AS meningitis_hos19m_total,
          SUM(meningitis_hos19f) AS meningitis_hos19f_total,
          SUM(meningitis_hos20m) AS meningitis_hos20m_total,
          SUM(meningitis_hos20f) AS meningitis_hos20f_total,
          SUM(meningitis_deaths5m) AS meningitis_deaths5m_total,
          SUM(meningitis_deaths5f) AS meningitis_deaths5f_total,
          SUM(meningitis_deaths19m) AS meningitis_deaths19m_total,
          SUM(meningitis_deaths19f) AS meningitis_deaths19f_total,
          SUM(meningitis_deaths20m) AS meningitis_deaths20m_total,
          SUM(meningitis_deaths20f) AS meningitis_deaths20f_total,
          SUM(measles_hos5m) AS measles_hos5m_total,
          SUM(measles_hos5f) AS measles_hos5f_total,
          SUM(measles_hos19m) AS measles_hos19m_total,
          SUM(measles_hos19f) AS measles_hos19f_total,
          SUM(measles_hos20m) AS measles_hos20m_total,
          SUM(measles_hos20f) AS measles_hos20f_total,
          SUM(measles_deaths5m) AS measles_deaths5m_total,
          SUM(measles_deaths5f) AS measles_deaths5f_total,
          SUM(measles_deaths19m) AS measles_deaths19m_total,
          SUM(measles_deaths19f) AS measles_deaths19f_total,
          SUM(measles_deaths20m) AS measles_deaths20m_total,
          SUM(measles_deaths20f) AS measles_deaths20f_total,
          SUM(tb_conf_hos5m) AS tb_conf_hos5m_total,
          SUM(tb_conf_hos5f) AS tb_conf_hos5f_total,
          SUM(tb_conf_hos19m) AS tb_conf_hos19m_total,
          SUM(tb_conf_hos19f) AS tb_conf_hos19f_total,
          SUM(tb_conf_hos20m) AS tb_conf_hos20m_total,
          SUM(tb_conf_hos20f) AS tb_conf_hos20f_total,
          SUM(tb_conf_deaths5m) AS tb_conf_deaths5m_total,
          SUM(tb_conf_deaths5f) AS tb_conf_deaths5f_total,
          SUM(tb_conf_deaths19m) AS tb_conf_deaths19m_total,
          SUM(tb_conf_deaths19f) AS tb_conf_deaths19f_total,
          SUM(tb_conf_deaths20m) AS tb_conf_deaths20m_total,
          SUM(tb_conf_deaths20f) AS tb_conf_deaths20f_total,
          SUM(tb_diag_hos5m) AS tb_diag_hos5m_total,
          SUM(tb_diag_hos5f) AS tb_diag_hos5f_total,
          SUM(tb_diag_hos19m) AS tb_diag_hos19m_total,
          SUM(tb_diag_hos19f) AS tb_diag_hos19f_total,
          SUM(tb_diag_hos20m) AS tb_diag_hos20m_total,
          SUM(tb_diag_hos20f) AS tb_diag_hos20f_total,
          SUM(tb_diag_deaths5m) AS tb_diag_deaths5m_total,
          SUM(tb_diag_deaths5f) AS tb_diag_deaths5f_total,
          SUM(tb_diag_deaths19m) AS tb_diag_deaths19m_total,
          SUM(tb_diag_deaths19f) AS tb_diag_deaths19f_total,
          SUM(tb_diag_deaths20m) AS tb_diag_deaths20m_total,
          SUM(tb_diag_deaths20f) AS tb_diag_deaths20f_total,
          SUM(fever_hos5m) AS fever_hos5m_total,
          SUM(fever_hos5f) AS fever_hos5f_total,
          SUM(fever_hos19m) AS fever_hos19m_total,
          SUM(fever_hos19f) AS fever_hos19f_total,
          SUM(fever_hos20m) AS fever_hos20m_total,
          SUM(fever_hos20f) AS fever_hos20f_total,
          SUM(fever_deaths5m) AS fever_deaths5m_total,
          SUM(fever_deaths5f) AS fever_deaths5f_total,
          SUM(fever_deaths19m) AS fever_deaths19m_total,
          SUM(fever_deaths19f) AS fever_deaths19f_total,
          SUM(fever_deaths20m) AS fever_deaths20m_total,
          SUM(fever_deaths20f) AS fever_deaths20f_total,
          SUM(encephalitis_hos5m) AS encephalitis_hos5m_total,
          SUM(encephalitis_hos5f) AS encephalitis_hos5f_total,
          SUM(encephalitis_hos19m) AS encephalitis_hos19m_total,
          SUM(encephalitis_hos19f) AS encephalitis_hos19f_total,
          SUM(encephalitis_hos20m) AS encephalitis_hos20m_total,
          SUM(encephalitis_hos20f) AS encephalitis_hos20f_total,
          SUM(encephalitis_deaths5m) AS encephalitis_deaths5m_total,
          SUM(encephalitis_deaths5f) AS encephalitis_deaths5f_total,
          SUM(encephalitis_deaths19m) AS encephalitis_deaths19m_total,
          SUM(encephalitis_deaths19f) AS encephalitis_deaths19f_total,
          SUM(encephalitis_deaths20m) AS encephalitis_deaths20m_total,
          SUM(encephalitis_deaths20f) AS encephalitis_deaths20f_total,
          SUM(mening_crypto_hos5m) AS mening_crypto_hos5m_total,
          SUM(mening_crypto_hos5f) AS mening_crypto_hos5f_total,
          SUM(mening_crypto_hos19m) AS mening_crypto_hos19m_total,
          SUM(mening_crypto_hos19f) AS mening_crypto_hos19f_total,
          SUM(mening_crypto_hos20m) AS mening_crypto_hos20m_total,
          SUM(mening_crypto_hos20f) AS mening_crypto_hos20f_total,
          SUM(mening_crypto_deaths5m) AS mening_crypto_deaths5m_total,
          SUM(mening_crypto_deaths5f) AS mening_crypto_deaths5f_total,
          SUM(mening_crypto_deaths19m) AS mening_crypto_deaths19m_total,
          SUM(mening_crypto_deaths19f) AS mening_crypto_deaths19f_total,
          SUM(mening_crypto_deaths20m) AS mening_crypto_deaths20m_total,
          SUM(mening_crypto_deaths20f) AS mening_crypto_deaths20f_total,
          SUM(skin_hos5m) AS skin_hos5m_total,
          SUM(skin_hos5f) AS skin_hos5f_total,
          SUM(skin_hos19m) AS skin_hos19m_total,
          SUM(skin_hos19f) AS skin_hos19f_total,
          SUM(skin_hos20m) AS skin_hos20m_total,
          SUM(skin_hos20f) AS skin_hos20f_total,
          SUM(skin_deaths5m) AS skin_deaths5m_total,
          SUM(skin_deaths5f) AS skin_deaths5f_total,
          SUM(skin_deaths19m) AS skin_deaths19m_total,
          SUM(skin_deaths19f) AS skin_deaths19f_total,
          SUM(skin_deaths20m) AS skin_deaths20m_total,
          SUM(skin_deaths20f) AS skin_deaths20f_total,
          SUM(diarr_chronic_hos5m) AS diarr_chronic_hos5m_total,
          SUM(diarr_chronic_hos5f) AS diarr_chronic_hos5f_total,
          SUM(diarr_chronic_hos19m) AS diarr_chronic_hos19m_total,
          SUM(diarr_chronic_hos19f) AS diarr_chronic_hos19f_total,
          SUM(diarr_chronic_hos20m) AS diarr_chronic_hos20m_total,
          SUM(diarr_chronic_hos20f) AS diarr_chronic_hos20f_total,
          SUM(diarr_chronic_deaths5m) AS diarr_chronic_deaths5m_total,
          SUM(diarr_chronic_deaths5f) AS diarr_chronic_deaths5f_total,
          SUM(diarr_chronic_deaths19m) AS diarr_chronic_deaths19m_total,
          SUM(diarr_chronic_deaths19f) AS diarr_chronic_deaths19f_total,
          SUM(diarr_chronic_deaths20m) AS diarr_chronic_deaths20m_total,
          SUM(diarr_chronic_deaths20f) AS diarr_chronic_deaths20f_total,
          SUM(hiv_hos5m) AS hiv_hos5m_total,
          SUM(hiv_hos5f) AS hiv_hos5f_total,
          SUM(hiv_hos19m) AS hiv_hos19m_total,
          SUM(hiv_hos19f) AS hiv_hos19f_total,
          SUM(hiv_hos20m) AS hiv_hos20m_total,
          SUM(hiv_hos20f) AS hiv_hos20f_total,
          SUM(hiv_deaths5m) AS hiv_deaths5m_total,
          SUM(hiv_deaths5f) AS hiv_deaths5f_total,
          SUM(hiv_deaths19m) AS hiv_deaths19m_total,
          SUM(hiv_deaths19f) AS hiv_deaths19f_total,
          SUM(hiv_deaths20m) AS hiv_deaths20m_total,
          SUM(hiv_deaths20f) AS hiv_deaths20f_total,
          SUM(trauma_hos5m) AS trauma_hos5m_total,
          SUM(trauma_hos5f) AS trauma_hos5f_total,
          SUM(trauma_hos19m) AS trauma_hos19m_total,
          SUM(trauma_hos19f) AS trauma_hos19f_total,
          SUM(trauma_hos20m) AS trauma_hos20m_total,
          SUM(trauma_hos20f) AS trauma_hos20f_total,
          SUM(trauma_deaths5m) AS trauma_deaths5m_total,
          SUM(trauma_deaths5f) AS trauma_deaths5f_total,
          SUM(trauma_deaths19m) AS trauma_deaths19m_total,
          SUM(trauma_deaths19f) AS trauma_deaths19f_total,
          SUM(trauma_deaths20m) AS trauma_deaths20m_total,
          SUM(trauma_deaths20f) AS trauma_deaths20f_total,
          SUM(spleen_hos5m) AS spleen_hos5m_total,
          SUM(spleen_hos5f) AS spleen_hos5f_total,
          SUM(spleen_hos19m) AS spleen_hos19m_total,
          SUM(spleen_hos19f) AS spleen_hos19f_total,
          SUM(spleen_hos20m) AS spleen_hos20m_total,
          SUM(spleen_hos20f) AS spleen_hos20f_total,
          SUM(spleen_deaths5m) AS spleen_deaths5m_total,
          SUM(spleen_deaths5f) AS spleen_deaths5f_total,
          SUM(spleen_deaths19m) AS spleen_deaths19m_total,
          SUM(spleen_deaths19f) AS spleen_deaths19f_total,
          SUM(spleen_deaths20m) AS spleen_deaths20m_total,
          SUM(spleen_deaths20f) AS spleen_deaths20f_total,
          SUM(frac_open_hos5m) AS frac_open_hos5m_total,
          SUM(frac_open_hos5f) AS frac_open_hos5f_total,
          SUM(frac_open_hos19m) AS frac_open_hos19m_total,
          SUM(frac_open_hos19f) AS frac_open_hos19f_total,
          SUM(frac_open_hos20m) AS frac_open_hos20m_total,
          SUM(frac_open_hos20f) AS frac_open_hos20f_total,
          SUM(frac_open_deaths5m) AS frac_open_deaths5m_total,
          SUM(frac_open_deaths5f) AS frac_open_deaths5f_total,
          SUM(frac_open_deaths19m) AS frac_open_deaths19m_total,
          SUM(frac_open_deaths19f) AS frac_open_deaths19f_total,
          SUM(frac_open_deaths20m) AS frac_open_deaths20m_total,
          SUM(frac_open_deaths20f) AS frac_open_deaths20f_total,
          SUM(frac_int_hos5m) AS frac_int_hos5m_total,
          SUM(frac_int_hos5f) AS frac_int_hos5f_total,
          SUM(frac_int_hos19m) AS frac_int_hos19m_total,
          SUM(frac_int_hos19f) AS frac_int_hos19f_total,
          SUM(frac_int_hos20m) AS frac_int_hos20m_total,
          SUM(frac_int_hos20f) AS frac_int_hos20f_total,
          SUM(frac_int_deaths5m) AS frac_int_deaths5m_total,
          SUM(frac_int_deaths5f) AS frac_int_deaths5f_total,
          SUM(frac_int_deaths19m) AS frac_int_deaths19m_total,
          SUM(frac_int_deaths19f) AS frac_int_deaths19f_total,
          SUM(frac_int_deaths20m) AS frac_int_deaths20m_total,
          SUM(frac_int_deaths20f) AS frac_int_deaths20f_total,
          SUM(trauma_other_hos5m) AS trauma_other_hos5m_total,
          SUM(trauma_other_hos5f) AS trauma_other_hos5f_total,
          SUM(trauma_other_hos19m) AS trauma_other_hos19m_total,
          SUM(trauma_other_hos19f) AS trauma_other_hos19f_total,
          SUM(trauma_other_hos20m) AS trauma_other_hos20m_total,
          SUM(trauma_other_hos20f) AS trauma_other_hos20f_total,
          SUM(trauma_other_deaths5m) AS trauma_other_deaths5m_total,
          SUM(trauma_other_deaths5f) AS trauma_other_deaths5f_total,
          SUM(trauma_other_deaths19m) AS trauma_other_deaths19m_total,
          SUM(trauma_other_deaths19f) AS trauma_other_deaths19f_total,
          SUM(trauma_other_deaths20m) AS trauma_other_deaths20m_total,
          SUM(trauma_other_deaths20f) AS trauma_other_deaths20f_total,
          SUM(burns_hos5m) AS burns_hos5m_total,
          SUM(burns_hos5f) AS burns_hos5f_total,
          SUM(burns_hos19m) AS burns_hos19m_total,
          SUM(burns_hos19f) AS burns_hos19f_total,
          SUM(burns_hos20m) AS burns_hos20m_total,
          SUM(burns_hos20f) AS burns_hos20f_total,
          SUM(burns_deaths5m) AS burns_deaths5m_total,
          SUM(burns_deaths5f) AS burns_deaths5f_total,
          SUM(burns_deaths19m) AS burns_deaths19m_total,
          SUM(burns_deaths19f) AS burns_deaths19f_total,
          SUM(burns_deaths20m) AS burns_deaths20m_total,
          SUM(burns_deaths20f) AS burns_deaths20f_total,
          SUM(hepatitis_hos5m) AS hepatitis_hos5m_total,
          SUM(hepatitis_hos5f) AS hepatitis_hos5f_total,
          SUM(hepatitis_hos19m) AS hepatitis_hos19m_total,
          SUM(hepatitis_hos19f) AS hepatitis_hos19f_total,
          SUM(hepatitis_hos20m) AS hepatitis_hos20m_total,
          SUM(hepatitis_hos20f) AS hepatitis_hos20f_total,
          SUM(hepatitis_deaths5m) AS hepatitis_deaths5m_total,
          SUM(hepatitis_deaths5f) AS hepatitis_deaths5f_total,
          SUM(hepatitis_deaths19m) AS hepatitis_deaths19m_total,
          SUM(hepatitis_deaths19f) AS hepatitis_deaths19f_total,
          SUM(hepatitis_deaths20m) AS hepatitis_deaths20m_total,
          SUM(hepatitis_deaths20f) AS hepatitis_deaths20f_total,
          SUM(cirrhosis_hos5m) AS cirrhosis_hos5m_total,
          SUM(cirrhosis_hos5f) AS cirrhosis_hos5f_total,
          SUM(cirrhosis_hos19m) AS cirrhosis_hos19m_total,
          SUM(cirrhosis_hos19f) AS cirrhosis_hos19f_total,
          SUM(cirrhosis_hos20m) AS cirrhosis_hos20m_total,
          SUM(cirrhosis_hos20f) AS cirrhosis_hos20f_total,
          SUM(cirrhosis_deaths5m) AS cirrhosis_deaths5m_total,
          SUM(cirrhosis_deaths5f) AS cirrhosis_deaths5f_total,
          SUM(cirrhosis_deaths19m) AS cirrhosis_deaths19m_total,
          SUM(cirrhosis_deaths19f) AS cirrhosis_deaths19f_total,
          SUM(cirrhosis_deaths20m) AS cirrhosis_deaths20m_total,
          SUM(cirrhosis_deaths20f) AS cirrhosis_deaths20f_total,
          SUM(digestive_hos5m) AS digestive_hos5m_total,
          SUM(digestive_hos5f) AS digestive_hos5f_total,
          SUM(digestive_hos19m) AS digestive_hos19m_total,
          SUM(digestive_hos19f) AS digestive_hos19f_total,
          SUM(digestive_hos20m) AS digestive_hos20m_total,
          SUM(digestive_hos20f) AS digestive_hos20f_total,
          SUM(digestive_deaths5m) AS digestive_deaths5m_total,
          SUM(digestive_deaths5f) AS digestive_deaths5f_total,
          SUM(digestive_deaths19m) AS digestive_deaths19m_total,
          SUM(digestive_deaths19f) AS digestive_deaths19f_total,
          SUM(digestive_deaths20m) AS digestive_deaths20m_total,
          SUM(digestive_deaths20f) AS digestive_deaths20f_total,
          SUM(gastritis_hos5m) AS gastritis_hos5m_total,
          SUM(gastritis_hos5f) AS gastritis_hos5f_total,
          SUM(gastritis_hos19m) AS gastritis_hos19m_total,
          SUM(gastritis_hos19f) AS gastritis_hos19f_total,
          SUM(gastritis_hos20m) AS gastritis_hos20m_total,
          SUM(gastritis_hos20f) AS gastritis_hos20f_total,
          SUM(gastritis_deaths5m) AS gastritis_deaths5m_total,
          SUM(gastritis_deaths5f) AS gastritis_deaths5f_total,
          SUM(gastritis_deaths19m) AS gastritis_deaths19m_total,
          SUM(gastritis_deaths19f) AS gastritis_deaths19f_total,
          SUM(gastritis_deaths20m) AS gastritis_deaths20m_total,
          SUM(gastritis_deaths20f) AS gastritis_deaths20f_total,
          SUM(ulcer_hos5m) AS ulcer_hos5m_total,
          SUM(ulcer_hos5f) AS ulcer_hos5f_total,
          SUM(ulcer_hos19m) AS ulcer_hos19m_total,
          SUM(ulcer_hos19f) AS ulcer_hos19f_total,
          SUM(ulcer_hos20m) AS ulcer_hos20m_total,
          SUM(ulcer_hos20f) AS ulcer_hos20f_total,
          SUM(ulcer_deaths5m) AS ulcer_deaths5m_total,
          SUM(ulcer_deaths5f) AS ulcer_deaths5f_total,
          SUM(ulcer_deaths19m) AS ulcer_deaths19m_total,
          SUM(ulcer_deaths19f) AS ulcer_deaths19f_total,
          SUM(ulcer_deaths20m) AS ulcer_deaths20m_total,
          SUM(ulcer_deaths20f) AS ulcer_deaths20f_total,
          SUM(appendi_hos5m) AS appendi_hos5m_total,
          SUM(appendi_hos5f) AS appendi_hos5f_total,
          SUM(appendi_hos19m) AS appendi_hos19m_total,
          SUM(appendi_hos19f) AS appendi_hos19f_total,
          SUM(appendi_hos20m) AS appendi_hos20m_total,
          SUM(appendi_hos20f) AS appendi_hos20f_total,
          SUM(appendi_deaths5m) AS appendi_deaths5m_total,
          SUM(appendi_deaths5f) AS appendi_deaths5f_total,
          SUM(appendi_deaths19m) AS appendi_deaths19m_total,
          SUM(appendi_deaths19f) AS appendi_deaths19f_total,
          SUM(appendi_deaths20m) AS appendi_deaths20m_total,
          SUM(appendi_deaths20f) AS appendi_deaths20f_total,
          SUM(hernia_hos5m) AS hernia_hos5m_total,
          SUM(hernia_hos5f) AS hernia_hos5f_total,
          SUM(hernia_hos19m) AS hernia_hos19m_total,
          SUM(hernia_hos19f) AS hernia_hos19f_total,
          SUM(hernia_hos20m) AS hernia_hos20m_total,
          SUM(hernia_hos20f) AS hernia_hos20f_total,
          SUM(hernia_deaths5m) AS hernia_deaths5m_total,
          SUM(hernia_deaths5f) AS hernia_deaths5f_total,
          SUM(hernia_deaths19m) AS hernia_deaths19m_total,
          SUM(hernia_deaths19f) AS hernia_deaths19f_total,
          SUM(hernia_deaths20m) AS hernia_deaths20m_total,
          SUM(hernia_deaths20f) AS hernia_deaths20f_total,
          SUM(peritonitis_hos5m) AS peritonitis_hos5m_total,
          SUM(peritonitis_hos5f) AS peritonitis_hos5f_total,
          SUM(peritonitis_hos19m) AS peritonitis_hos19m_total,
          SUM(peritonitis_hos19f) AS peritonitis_hos19f_total,
          SUM(peritonitis_hos20m) AS peritonitis_hos20m_total,
          SUM(peritonitis_hos20f) AS peritonitis_hos20f_total,
          SUM(peritonitis_deaths5m) AS peritonitis_deaths5m_total,
          SUM(peritonitis_deaths5f) AS peritonitis_deaths5f_total,
          SUM(peritonitis_deaths19m) AS peritonitis_deaths19m_total,
          SUM(peritonitis_deaths19f) AS peritonitis_deaths19f_total,
          SUM(peritonitis_deaths20m) AS peritonitis_deaths20m_total,
          SUM(peritonitis_deaths20f) AS peritonitis_deaths20f_total,
          SUM(intestinal_hos5m) AS intestinal_hos5m_total,
          SUM(intestinal_hos5f) AS intestinal_hos5f_total,
          SUM(intestinal_hos19m) AS intestinal_hos19m_total,
          SUM(intestinal_hos19f) AS intestinal_hos19f_total,
          SUM(intestinal_hos20m) AS intestinal_hos20m_total,
          SUM(intestinal_hos20f) AS intestinal_hos20f_total,
          SUM(intestinal_deaths5m) AS intestinal_deaths5m_total,
          SUM(intestinal_deaths5f) AS intestinal_deaths5f_total,
          SUM(intestinal_deaths19m) AS intestinal_deaths19m_total,
          SUM(intestinal_deaths19f) AS intestinal_deaths19f_total,
          SUM(intestinal_deaths20m) AS intestinal_deaths20m_total,
          SUM(intestinal_deaths20f) AS intestinal_deaths20f_total,
          SUM(urinary_hos5m) AS urinary_hos5m_total,
          SUM(urinary_hos5f) AS urinary_hos5f_total,
          SUM(urinary_hos19m) AS urinary_hos19m_total,
          SUM(urinary_hos19f) AS urinary_hos19f_total,
          SUM(urinary_hos20m) AS urinary_hos20m_total,
          SUM(urinary_hos20f) AS urinary_hos20f_total,
          SUM(urinary_deaths5m) AS urinary_deaths5m_total,
          SUM(urinary_deaths5f) AS urinary_deaths5f_total,
          SUM(urinary_deaths19m) AS urinary_deaths19m_total,
          SUM(urinary_deaths19f) AS urinary_deaths19f_total,
          SUM(urinary_deaths20m) AS urinary_deaths20m_total,
          SUM(urinary_deaths20f) AS urinary_deaths20f_total,
          SUM(bone_inf_hos5m) AS bone_inf_hos5m_total,
          SUM(bone_inf_hos5f) AS bone_inf_hos5f_total,
          SUM(bone_inf_hos19m) AS bone_inf_hos19m_total,
          SUM(bone_inf_hos19f) AS bone_inf_hos19f_total,
          SUM(bone_inf_hos20m) AS bone_inf_hos20m_total,
          SUM(bone_inf_hos20f) AS bone_inf_hos20f_total,
          SUM(bone_inf_deaths5m) AS bone_inf_deaths5m_total,
          SUM(bone_inf_deaths5f) AS bone_inf_deaths5f_total,
          SUM(bone_inf_deaths19m) AS bone_inf_deaths19m_total,
          SUM(bone_inf_deaths19f) AS bone_inf_deaths19f_total,
          SUM(bone_inf_deaths20m) AS bone_inf_deaths20m_total,
          SUM(bone_inf_deaths20f) AS bone_inf_deaths20f_total,
          SUM(bone_other_hos5m) AS bone_other_hos5m_total,
          SUM(bone_other_hos5f) AS bone_other_hos5f_total,
          SUM(bone_other_hos19m) AS bone_other_hos19m_total,
          SUM(bone_other_hos19f) AS bone_other_hos19f_total,
          SUM(bone_other_hos20m) AS bone_other_hos20m_total,
          SUM(bone_other_hos20f) AS bone_other_hos20f_total,
          SUM(bone_other_deaths5m) AS bone_other_deaths5m_total,
          SUM(bone_other_deaths5f) AS bone_other_deaths5f_total,
          SUM(bone_other_deaths19m) AS bone_other_deaths19m_total,
          SUM(bone_other_deaths19f) AS bone_other_deaths19f_total,
          SUM(bone_other_deaths20m) AS bone_other_deaths20m_total,
          SUM(bone_other_deaths20f) AS bone_other_deaths20f_total,
          SUM(acute_hos5m) AS acute_hos5m_total,
          SUM(acute_hos5f) AS acute_hos5f_total,
          SUM(acute_hos19m) AS acute_hos19m_total,
          SUM(acute_hos19f) AS acute_hos19f_total,
          SUM(acute_hos20m) AS acute_hos20m_total,
          SUM(acute_hos20f) AS acute_hos20f_total,
          SUM(acute_deaths5m) AS acute_deaths5m_total,
          SUM(acute_deaths5f) AS acute_deaths5f_total,
          SUM(acute_deaths19m) AS acute_deaths19m_total,
          SUM(acute_deaths19f) AS acute_deaths19f_total,
          SUM(acute_deaths20m) AS acute_deaths20m_total,
          SUM(acute_deaths20f) AS acute_deaths20f_total,
          SUM(gyneco_hos5f) AS gyneco_hos5f_total,
          SUM(gyneco_hos19f) AS gyneco_hos19f_total,
          SUM(gyneco_hos20f) AS gyneco_hos20f_total,
          SUM(gyneco_deaths19f) AS gyneco_deaths19f_total,
          SUM(gyneco_deaths20f) AS gyneco_deaths20f_total,
          SUM(mastoditis_hos5m) AS mastoditis_hos5m_total,
          SUM(mastoditis_hos5f) AS mastoditis_hos5f_total,
          SUM(mastoditis_hos19m) AS mastoditis_hos19m_total,
          SUM(mastoditis_hos19f) AS mastoditis_hos19f_total,
          SUM(mastoditis_hos20m) AS mastoditis_hos20m_total,
          SUM(mastoditis_hos20f) AS mastoditis_hos20f_total,
          SUM(mastoditis_deaths5m) AS mastoditis_deaths5m_total,
          SUM(mastoditis_deaths5f) AS mastoditis_deaths5f_total,
          SUM(mastoditis_deaths19m) AS mastoditis_deaths19m_total,
          SUM(mastoditis_deaths19f) AS mastoditis_deaths19f_total,
          SUM(mastoditis_deaths20m) AS mastoditis_deaths20m_total,
          SUM(mastoditis_deaths20f) AS mastoditis_deaths20f_total,
          SUM(tetanus_hos5m) AS tetanus_hos5m_total,
          SUM(tetanus_hos5f) AS tetanus_hos5f_total,
          SUM(tetanus_hos19m) AS tetanus_hos19m_total,
          SUM(tetanus_hos19f) AS tetanus_hos19f_total,
          SUM(tetanus_hos20m) AS tetanus_hos20m_total,
          SUM(tetanus_hos20f) AS tetanus_hos20f_total,
          SUM(tetanus_deaths5m) AS tetanus_deaths5m_total,
          SUM(tetanus_deaths5f) AS tetanus_deaths5f_total,
          SUM(tetanus_deaths19m) AS tetanus_deaths19m_total,
          SUM(tetanus_deaths19f) AS tetanus_deaths19f_total,
          SUM(tetanus_deaths20m) AS tetanus_deaths20m_total,
          SUM(tetanus_deaths20f) AS tetanus_deaths20f_total,
          SUM(cancer_hos5m) AS cancer_hos5m_total,
          SUM(cancer_hos5f) AS cancer_hos5f_total,
          SUM(cancer_hos19m) AS cancer_hos19m_total,
          SUM(cancer_hos19f) AS cancer_hos19f_total,
          SUM(cancer_hos20m) AS cancer_hos20m_total,
          SUM(cancer_hos20f) AS cancer_hos20f_total,
          SUM(cancer_deaths5m) AS cancer_deaths5m_total,
          SUM(cancer_deaths5f) AS cancer_deaths5f_total,
          SUM(cancer_deaths19m) AS cancer_deaths19m_total,
          SUM(cancer_deaths19f) AS cancer_deaths19f_total,
          SUM(cancer_deaths20m) AS cancer_deaths20m_total,
          SUM(cancer_deaths20f) AS cancer_deaths20f_total
        ");
        $this->db->from('Hospitalization_BCDE');
        $this->db->where('date_hospitalization_bcde', $date);
        return $this->db->get()->row();
    }

    public function physiotherapy($date)
    {
        return $this->db->get_where('Physiotherapy', array('date_physiotherapy' => $date))->row();
    }

    public function delivery_birth($date)
    {
        return $this->db->get_where('Delivery_Birth', array('date_delivery_birth' => $date))->row();
    }

    public function postnatal_care($date)
    {
        return $this->db->get_where('Postnatal_Care', array('date_postnatal_care' => $date))->row();
    }

    public function kangaroo_mother_care($date)
    {
        return $this->db->get_where('Kangaroo_Mother_Care', array('date_kangaroo_mother_care' => $date))->row();
    }

    public function family_planning($date)
    {
        return $this->db->get_where('Family_Planning', array('date_family_planning' => $date))->row();
    }

    public function laboratory($date)
    {
        return $this->db->get_where('Laboratory', array('date_laboratory' => $date))->row();
    }

    public function blood_bank_security($date)
    {
        return $this->db->get_where('Blood_Bank_Security', array('date_blood_bank_security' => $date))->row();
    }

    public function consultation_abcde($date)
    {
        $this->db->select("
      SUM(nc5m) as nc5m_total,
      SUM(nc5f) as nc5f_total,
      SUM(nc19m) as nc19m_total,
      SUM(nc19f) as nc19f_total,
      SUM(nc20m) as nc20m_total,
      SUM(nc20f) as nc20f_total,
      SUM(oc5m) as oc5m_total,
      SUM(oc5f) as oc5f_total,
      SUM(oc19m) as oc19m_total,
      SUM(oc19f) as oc19f_total,
      SUM(oc20m) as oc20m_total,
      SUM(oc20f) as oc20f_total,

      SUM(insured) as insured_total,
      SUM(nc_non_paying) as nc_non_paying_total,
      SUM(nc_indigent) as nc_indigent_total,

      SUM(other_levels) as other_levels_total,
      SUM(counter_received) as counter_received_total,

      SUM(nc_catch) as nc_catch_total,
      SUM(nc) as nc_total,
      SUM(international) as international_total,

      SUM(diar_w_dehy_5m) as diar_w_dehy_5m_total,
      SUM(diar_w_dehy_5f) as diar_w_dehy_5f_total,
      SUM(diar_w_dehy_19m) as diar_w_dehy_19m_total,
      SUM(diar_w_dehy_19f) as diar_w_dehy_19f_total,
      SUM(diar_w_dehy_20m) as diar_w_dehy_20m_total,
      SUM(diar_w_dehy_20f) as diar_w_dehy_20f_total,
      SUM(diar_no_dehy_5m) as diar_no_dehy_5m_total,
      SUM(diar_no_dehy_5f) as diar_no_dehy_5f_total,
      SUM(diar_no_dehy_19m) as diar_no_dehy_19m_total,
      SUM(diar_no_dehy_19f) as diar_no_dehy_19f_total,
      SUM(diar_no_dehy_20m) as diar_no_dehy_20m_total,
      SUM(diar_no_dehy_20f) as diar_no_dehy_20f_total,
      SUM(blood_diar_5m) as blood_diar_5m_total,
      SUM(blood_diar_5f) as blood_diar_5f_total,
      SUM(blood_diar_19m) as blood_diar_19m_total,
      SUM(blood_diar_19f) as blood_diar_19f_total,
      SUM(blood_diar_20m) as blood_diar_20m_total,
      SUM(blood_diar_20f) as blood_diar_20f_total,
      SUM(food_poison_5m) as food_poison_5m_total,
      SUM(food_poison_5f) as food_poison_5f_total,
      SUM(food_poison_19m) as food_poison_19m_total,
      SUM(food_poison_19f) as food_poison_19f_total,
      SUM(food_poison_20m) as food_poison_20m_total,
      SUM(food_poison_20f) as food_poison_20f_total,
      SUM(ear_infect_5m) as ear_infect_5m_total,
      SUM(ear_infect_5f) as ear_infect_5f_total,
      SUM(ear_infect_19m) as ear_infect_19m_total,
      SUM(ear_infect_19f) as ear_infect_19f_total,
      SUM(ear_infect_20m) as ear_infect_20m_total,
      SUM(ear_infect_20f) as ear_infect_20f_total,
      SUM(schisto_5m) as schisto_5m_total,
      SUM(schisto_5f) as schisto_5f_total,
      SUM(schisto_19m) as schisto_19m_total,
      SUM(schisto_19f) as schisto_19f_total,
      SUM(schisto_20m) as schisto_20m_total,
      SUM(schisto_20f) as schisto_20f_total,
      SUM(ascaris_5m) as ascaris_5m_total,
      SUM(ascaris_5f) as ascaris_5f_total,
      SUM(ascaris_19m) as ascaris_19m_total,
      SUM(ascaris_19f) as ascaris_19f_total,
      SUM(ascaris_20m) as ascaris_20m_total,
      SUM(ascaris_20f) as ascaris_20f_total,
      SUM(trichu_5m) as trichu_5m_total,
      SUM(trichu_5f) as trichu_5f_total,
      SUM(trichu_19m) as trichu_19m_total,
      SUM(trichu_19f) as trichu_19f_total,
      SUM(trichu_20m) as trichu_20m_total,
      SUM(trichu_20f) as trichu_20f_total,
      SUM(hook_5m) as hook_5m_total,
      SUM(hook_5f) as hook_5f_total,
      SUM(hook_19m) as hook_19m_total,
      SUM(hook_19f) as hook_19f_total,
      SUM(hook_20m) as hook_20m_total,
      SUM(hook_20f) as hook_20f_total,
      SUM(entam_5m) as entam_5m_total,
      SUM(entam_5f) as entam_5f_total,
      SUM(entam_19m) as entam_19m_total,
      SUM(entam_19f) as entam_19f_total,
      SUM(entam_20m) as entam_20m_total,
      SUM(entam_20f) as entam_20f_total,
      SUM(giardia_5m) as giardia_5m_total,
      SUM(giardia_5f) as giardia_5f_total,
      SUM(giardia_19m) as giardia_19m_total,
      SUM(giardia_19f) as giardia_19f_total,
      SUM(giardia_20m) as giardia_20m_total,
      SUM(giardia_20f) as giardia_20f_total,
      SUM(taenia_5m) as taenia_5m_total,
      SUM(taenia_5f) as taenia_5f_total,
      SUM(taenia_19m) as taenia_19m_total,
      SUM(taenia_19f) as taenia_19f_total,
      SUM(taenia_20m) as taenia_20m_total,
      SUM(taenia_20f) as taenia_20f_total,
      SUM(malaria_s_5m) as malaria_s_5m_total,
      SUM(malaria_s_5f) as malaria_s_5f_total,
      SUM(malaria_s_19m) as malaria_s_19m_total,
      SUM(malaria_s_19f) as malaria_s_19f_total,
      SUM(malaria_s_20m) as malaria_s_20m_total,
      SUM(malaria_s_20f) as malaria_s_20f_total,
      SUM(malaria_dig_5m) as malaria_dig_5m_total,
      SUM(malaria_dig_5f) as malaria_dig_5f_total,
      SUM(malaria_dig_19m) as malaria_dig_19m_total,
      SUM(malaria_dig_19f) as malaria_dig_19f_total,
      SUM(malaria_dig_20m) as malaria_dig_20m_total,
      SUM(malaria_dig_20f) as malaria_dig_20f_total,
      SUM(herpes_s_5m) as herpes_s_5m_total,
      SUM(herpes_s_5f) as herpes_s_5f_total,
      SUM(herpes_s_19m) as herpes_s_19m_total,
      SUM(herpes_s_19f) as herpes_s_19f_total,
      SUM(herpes_s_20m) as herpes_s_20m_total,
      SUM(herpes_s_20f) as herpes_s_20f_total,
      SUM(mening_5m) as mening_5m_total,
      SUM(mening_5f) as mening_5f_total,
      SUM(mening_19m) as mening_19m_total,
      SUM(mening_19f) as mening_19f_total,
      SUM(mening_20m) as mening_20m_total,
      SUM(mening_20f) as mening_20f_total,
      SUM(pneumonia_simp_5m) as pneumonia_simp_5m_total,
      SUM(pneumonia_simp_5f) as pneumonia_simp_5f_total,
      SUM(pneumonia_simp_19m) as pneumonia_simp_19m_total,
      SUM(pneumonia_simp_19f) as pneumonia_simp_19f_total,
      SUM(pneumonia_simp_20m) as pneumonia_simp_20m_total,
      SUM(pneumonia_simp_20f) as pneumonia_simp_20f_total,
      SUM(pneumonia_sev_5m) as pneumonia_sev_5m_total,
      SUM(pneumonia_sev_5f) as pneumonia_sev_5f_total,
      SUM(pneumonia_sev_19m) as pneumonia_sev_19m_total,
      SUM(pneumonia_sev_19f) as pneumonia_sev_19f_total,
      SUM(pneumonia_sev_20m) as pneumonia_sev_20m_total,
      SUM(pneumonia_sev_20f) as pneumonia_sev_20f_total,
      SUM(grip_5m) as grip_5m_total,
      SUM(grip_5f) as grip_5f_total,
      SUM(grip_19m) as grip_19m_total,
      SUM(grip_19f) as grip_19f_total,
      SUM(grip_20m) as grip_20m_total,
      SUM(grip_20f) as grip_20f_total,
      SUM(ari_5m) as ari_5m_total,
      SUM(ari_5f) as ari_5f_total,
      SUM(ari_19m) as ari_19m_total,
      SUM(ari_19f) as ari_19f_total,
      SUM(ari_20m) as ari_20m_total,
      SUM(ari_20f) as ari_20f_total,
      SUM(gast_duoden_5m) as gast_duoden_5m_total,
      SUM(gast_duoden_5f) as gast_duoden_5f_total,
      SUM(gast_duoden_19m) as gast_duoden_19m_total,
      SUM(gast_duoden_19f) as gast_duoden_19f_total,
      SUM(gast_duoden_20m) as gast_duoden_20m_total,
      SUM(gast_duoden_20f) as gast_duoden_20f_total,
      SUM(absces_5m) as absces_5m_total,
      SUM(absces_5f) as absces_5f_total,
      SUM(absces_19m) as absces_19m_total,
      SUM(absces_19f) as absces_19f_total,
      SUM(absces_20m) as absces_20m_total,
      SUM(absces_20f) as absces_20f_total,
      SUM(ulcers_5m) as ulcers_5m_total,
      SUM(ulcers_5f) as ulcers_5f_total,
      SUM(ulcers_19m) as ulcers_19m_total,
      SUM(ulcers_19f) as ulcers_19f_total,
      SUM(ulcers_20m) as ulcers_20m_total,
      SUM(ulcers_20f) as ulcers_20f_total,
      SUM(scabies_5m) as scabies_5m_total,
      SUM(scabies_5f) as scabies_5f_total,
      SUM(scabies_19m) as scabies_19m_total,
      SUM(scabies_19f) as scabies_19f_total,
      SUM(scabies_20m) as scabies_20m_total,
      SUM(scabies_20f) as scabies_20f_total,
      SUM(mycoses_5m) as mycoses_5m_total,
      SUM(mycoses_5f) as mycoses_5f_total,
      SUM(mycoses_19m) as mycoses_19m_total,
      SUM(mycoses_19f) as mycoses_19f_total,
      SUM(mycoses_20m) as mycoses_20m_total,
      SUM(mycoses_20f) as mycoses_20f_total,
      SUM(si_others_5m) as si_others_5m_total,
      SUM(si_others_5f) as si_others_5f_total,
      SUM(si_others_19m) as si_others_19m_total,
      SUM(si_others_19f) as si_others_19f_total,
      SUM(si_others_20m) as si_others_20m_total,
      SUM(si_others_20f) as si_others_20f_total,
      SUM(urinary_ti_5m) as urinary_ti_5m_total,
      SUM(urinary_ti_5f) as urinary_ti_5f_total,
      SUM(urinary_ti_19m) as urinary_ti_19m_total,
      SUM(urinary_ti_19f) as urinary_ti_19f_total,
      SUM(urinary_ti_20m) as urinary_ti_20m_total,
      SUM(urinary_ti_20f) as urinary_ti_20f_total,
      SUM(anemia_5m) as anemia_5m_total,
      SUM(anemia_5f) as anemia_5f_total,
      SUM(anemia_19m) as anemia_19m_total,
      SUM(anemia_19f) as anemia_19f_total,
      SUM(anemia_20m) as anemia_20m_total,
      SUM(anemia_20f) as anemia_20f_total,
      SUM(measles_susp_5m) as measles_susp_5m_total,
      SUM(measles_susp_5f) as measles_susp_5f_total,
      SUM(measles_susp_19m) as measles_susp_19m_total,
      SUM(measles_susp_19f) as measles_susp_19f_total,
      SUM(measles_susp_20m) as measles_susp_20m_total,
      SUM(measles_susp_20f) as measles_susp_20f_total,
      SUM(measles_conf_5m) as measles_conf_5m_total,
      SUM(measles_conf_5f) as measles_conf_5f_total,
      SUM(measles_conf_19m) as measles_conf_19m_total,
      SUM(measles_conf_19f) as measles_conf_19f_total,
      SUM(measles_conf_20m) as measles_conf_20m_total,
      SUM(measles_conf_20f) as measles_conf_20f_total,
      SUM(rubella_conf_5m) as rubella_conf_5m_total,
      SUM(rubella_conf_5f) as rubella_conf_5f_total,
      SUM(rubella_conf_19m) as rubella_conf_19m_total,
      SUM(rubella_conf_19f) as rubella_conf_19f_total,
      SUM(rubella_conf_20m) as rubella_conf_20m_total,
      SUM(rubella_conf_20f) as rubella_conf_20f_total,
      SUM(flaccid_paraly_5m) as flaccid_paraly_5m_total,
      SUM(flaccid_paraly_5f) as flaccid_paraly_5f_total,
      SUM(flaccid_paraly_19m) as flaccid_paraly_19m_total,
      SUM(flaccid_paraly_19f) as flaccid_paraly_19f_total,
      SUM(flaccid_paraly_20m) as flaccid_paraly_20m_total,
      SUM(flaccid_paraly_20f) as flaccid_paraly_20f_total,
      SUM(tetanus_5m) as tetanus_5m_total,
      SUM(tetanus_5f) as tetanus_5f_total,
      SUM(tetanus_19m) as tetanus_19m_total,
      SUM(tetanus_19f) as tetanus_19f_total,
      SUM(tetanus_20m) as tetanus_20m_total,
      SUM(tetanus_20f) as tetanus_20f_total,
      SUM(hepatitis_5m) as hepatitis_5m_total,
      SUM(hepatitis_5f) as hepatitis_5f_total,
      SUM(hepatitis_19m) as hepatitis_19m_total,
      SUM(hepatitis_19f) as hepatitis_19f_total,
      SUM(hepatitis_20m) as hepatitis_20m_total,
      SUM(hepatitis_20f) as hepatitis_20f_total
      ");
        $this->db->from('consultation_abcde');
        $this->db->where('date_consultation_abcde', $date);
        return $this->db->get()->row();
    }

    public function consultation_fg($date)
    {
        $this->db->select("
      SUM(fractures_5m) as fractures_5m_total,
      SUM(fractures_5f) as fractures_5f_total,
      SUM(fractures_19m) as fractures_19m_total,
      SUM(fractures_19f) as fractures_19f_total,
      SUM(fractures_20m) as fractures_20m_total,
      SUM(fractures_20f) as fractures_20f_total,
      SUM(phys_traumas_5m) as phys_traumas_5m_total,
      SUM(phys_traumas_5f) as phys_traumas_5f_total,
      SUM(phys_traumas_19m) as phys_traumas_19m_total,
      SUM(phys_traumas_19f) as phys_traumas_19f_total,
      SUM(phys_traumas_20m) as phys_traumas_20m_total,
      SUM(phys_traumas_20f) as phys_traumas_20f_total,
      SUM(bone_joint_disord_5m) as bone_joint_disord_5m_total,
      SUM(bone_joint_disord_5f) as bone_joint_disord_5f_total,
      SUM(bone_joint_disord_19m) as bone_joint_disord_19m_total,
      SUM(bone_joint_disord_19f) as bone_joint_disord_19f_total,
      SUM(bone_joint_disord_20m) as bone_joint_disord_20m_total,
      SUM(bone_joint_disord_20f) as bone_joint_disord_20f_total,
      SUM(gyneco_pb_19f) as gyneco_pb_19f_total,
      SUM(gyneco_pb_20f) as gyneco_pb_20f_total,
      SUM(aids_5m) as aids_5m_total,
      SUM(aids_5f) as aids_5f_total,
      SUM(aids_19m) as aids_19m_total,
      SUM(aids_19f) as aids_19f_total,
      SUM(aids_20m) as aids_20m_total,
      SUM(aids_20f) as aids_20f_total,
      SUM(si_opport_5m) as si_opport_5m_total,
      SUM(si_opport_5f) as si_opport_5f_total,
      SUM(si_opport_19m) as si_opport_19m_total,
      SUM(si_opport_19f) as si_opport_19f_total,
      SUM(si_opport_20m) as si_opport_20m_total,
      SUM(si_opport_20f) as si_opport_20f_total,
      SUM(herpes_z_5m) as herpes_z_5m_total,
      SUM(herpes_z_5f) as herpes_z_5f_total,
      SUM(herpes_z_19m) as herpes_z_19m_total,
      SUM(herpes_z_19f) as herpes_z_19f_total,
      SUM(herpes_z_20m) as herpes_z_20m_total,
      SUM(herpes_z_20f) as herpes_z_20f_total,
      SUM(cand_oral_5m) as cand_oral_5m_total,
      SUM(cand_oral_5f) as cand_oral_5f_total,
      SUM(cand_oral_19m) as cand_oral_19m_total,
      SUM(cand_oral_19f) as cand_oral_19f_total,
      SUM(cand_oral_20m) as cand_oral_20m_total,
      SUM(cand_oral_20f) as cand_oral_20f_total,
      SUM(fever_5m) as fever_5m_total,
      SUM(fever_5f) as fever_5f_total,
      SUM(fever_19m) as fever_19m_total,
      SUM(fever_19f) as fever_19f_total,
      SUM(fever_20m) as fever_20m_total,
      SUM(fever_20f) as fever_20f_total,
      SUM(diar_chro_opp_infect_5m) as diar_chro_opp_infect_5m_total,
      SUM(diar_chro_opp_infect_5f) as diar_chro_opp_infect_5f_total,
      SUM(diar_chro_opp_infect_19m) as diar_chro_opp_infect_19m_total,
      SUM(diar_chro_opp_infect_19f) as diar_chro_opp_infect_19f_total,
      SUM(diar_chro_opp_infect_20m) as diar_chro_opp_infect_20m_total,
      SUM(diar_chro_opp_infect_20f) as diar_chro_opp_infect_20f_total,
      SUM(needle_5m) as needle_5m_total,
      SUM(needle_5f) as needle_5f_total,
      SUM(needle_19m) as needle_19m_total,
      SUM(needle_19f) as needle_19f_total,
      SUM(needle_20m) as needle_20m_total,
      SUM(needle_20f) as needle_20f_total,
      SUM(goitre_5m) as goitre_5m_total,
      SUM(goitre_5f) as goitre_5f_total,
      SUM(goitre_19m) as goitre_19m_total,
      SUM(goitre_19f) as goitre_19f_total,
      SUM(goitre_20m) as goitre_20m_total,
      SUM(goitre_20f) as goitre_20f_total,
      SUM(va_def_5m) as va_def_5m_total,
      SUM(va_def_5f) as va_def_5f_total,
      SUM(va_def_19m) as va_def_19m_total,
      SUM(va_def_19f) as va_def_19f_total,
      SUM(va_def_20m) as va_def_20m_total,
      SUM(va_def_20f) as va_def_20f_total,
      SUM(leprosy_5m) as leprosy_5m_total,
      SUM(leprosy_5f) as leprosy_5f_total,
      SUM(leprosy_19m) as leprosy_19m_total,
      SUM(leprosy_19f) as leprosy_19f_total,
      SUM(leprosy_20m) as leprosy_20m_total,
      SUM(leprosy_20f) as leprosy_20f_total,

      SUM(glaucoma_19m) as glaucoma_19m_total,
      SUM(glaucoma_19f) as glaucoma_19f_total,
      SUM(glaucoma_39m) as glaucoma_39m_total,
      SUM(glaucoma_39f) as glaucoma_39f_total,
      SUM(glaucoma_40m) as glaucoma_40m_total,
      SUM(glaucoma_40f) as glaucoma_40f_total,
      SUM(cataract_19m) as cataract_19m_total,
      SUM(cataract_19f) as cataract_19f_total,
      SUM(cataract_39m) as cataract_39m_total,
      SUM(cataract_39f) as cataract_39f_total,
      SUM(cataract_40m) as cataract_40m_total,
      SUM(cataract_40f) as cataract_40f_total,
      SUM(refrac_error_19m) as refrac_error_19m_total,
      SUM(refrac_error_19f) as refrac_error_19f_total,
      SUM(refrac_error_39m) as refrac_error_39m_total,
      SUM(refrac_error_39f) as refrac_error_39f_total,
      SUM(refrac_error_40m) as refrac_error_40m_total,
      SUM(refrac_error_40f) as refrac_error_40f_total,
      SUM(diab_retino_19m) as diab_retino_19m_total,
      SUM(diab_retino_19f) as diab_retino_19f_total,
      SUM(diab_retino_39m) as diab_retino_39m_total,
      SUM(diab_retino_39f) as diab_retino_39f_total,
      SUM(diab_retino_40m) as diab_retino_40m_total,
      SUM(diab_retino_40f) as diab_retino_40f_total,
      SUM(conjunctivitis_19m) as conjunctivitis_19m_total,
      SUM(conjunctivitis_19f) as conjunctivitis_19f_total,
      SUM(conjunctivitis_39m) as conjunctivitis_39m_total,
      SUM(conjunctivitis_39f) as conjunctivitis_39f_total,
      SUM(conjunctivitis_40m) as conjunctivitis_40m_total,
      SUM(conjunctivitis_40f) as conjunctivitis_40f_total,
      SUM(pinguecula_19m) as pinguecula_19m_total,
      SUM(pinguecula_19f) as pinguecula_19f_total,
      SUM(pinguecula_39m) as pinguecula_39m_total,
      SUM(pinguecula_39f) as pinguecula_39f_total,
      SUM(pinguecula_40m) as pinguecula_40m_total,
      SUM(pinguecula_40f) as pinguecula_40f_total,
      SUM(uveitis_19m) as uveitis_19m_total,
      SUM(uveitis_19f) as uveitis_19f_total,
      SUM(uveitis_39m) as uveitis_39m_total,
      SUM(uveitis_39f) as uveitis_39f_total,
      SUM(uveitis_40m) as uveitis_40m_total,
      SUM(uveitis_40f) as uveitis_40f_total,
      SUM(eye_trauma_19m) as eye_trauma_19m_total,
      SUM(eye_trauma_19f) as eye_trauma_19f_total,
      SUM(eye_trauma_39m) as eye_trauma_39m_total,
      SUM(eye_trauma_39f) as eye_trauma_39f_total,
      SUM(eye_trauma_40m) as eye_trauma_40m_total,
      SUM(eye_trauma_40f) as eye_trauma_40f_total,
      SUM(eye_pb_19m) as eye_pb_19m_total,
      SUM(eye_pb_19f) as eye_pb_19f_total,
      SUM(eye_pb_39m) as eye_pb_39m_total,
      SUM(eye_pb_39f) as eye_pb_39f_total,
      SUM(eye_pb_40m) as eye_pb_40m_total,
      SUM(eye_pb_40f) as eye_pb_40f_total,
      SUM(dent_caries_19m) as dent_caries_19m_total,
      SUM(dent_caries_19f) as dent_caries_19f_total,
      SUM(dent_caries_39m) as dent_caries_39m_total,
      SUM(dent_caries_39f) as dent_caries_39f_total,
      SUM(dent_caries_40m) as dent_caries_40m_total,
      SUM(dent_caries_40f) as dent_caries_40f_total,
      SUM(perio_diseas_19m) as perio_diseas_19m_total,
      SUM(perio_diseas_19f) as perio_diseas_19f_total,
      SUM(perio_diseas_39m) as perio_diseas_39m_total,
      SUM(perio_diseas_39f) as perio_diseas_39f_total,
      SUM(perio_diseas_40m) as perio_diseas_40m_total,
      SUM(perio_diseas_40f) as perio_diseas_40f_total,
      SUM(other_teeth_19m) as other_teeth_19m_total,
      SUM(other_teeth_19f) as other_teeth_19f_total,
      SUM(other_teeth_39m) as other_teeth_39m_total,
      SUM(other_teeth_39f) as other_teeth_39f_total,
      SUM(other_teeth_40m) as other_teeth_40m_total,
      SUM(other_teeth_40f) as other_teeth_40f_total
      ");
        $this->db->from('consultation_fg');
        $this->db->where('date_consultation_fg', $date);
        return $this->db->get()->row();
    }

    public function chronic_disease($date)
    {
        return $this->db->get_where('chronic_disease', array('date_chronic_disease' => $date))->row();
    }

    public function injury($date)
    {
        return $this->db->get_where('injury', array('date_injury' => $date))->row();
    }

    public function GBV($date)
    {
        return $this->db->get_where('gender_based_violence', array('date_gender_based_violence' => $date))->row();
    }

    public function anesthesia($date)
    {
        $this->db->select("
      SUM(general) as general_total,
      SUM(regional) as regional_total,
      SUM(local) as local_total,
      SUM(other_type) as other_type_total
      ");
        $this->db->from('anesthesia');
        $this->db->where('date_anesthesia', $date);
        return $this->db->get()->row();
    }

    public function obstetrical_a($date)
    {
        return $this->db->get_where('obstetrical_complication_a', array('date_obstetrical_complication_a' => $date))->row();
    }

    public function obstetrical_bc($date)
    {
        $this->db->select("
      SUM(intra_antibio) as intra_antibio_total,
      SUM(mother_uterotonic) as mother_uterotonic_total,
      SUM(manual_placenta) as manual_placenta_total,
      SUM(post_abortion) as post_abortion_total,
      SUM(vacuum_extraction) as vacuum_extraction_total,
      SUM(Preeclampsia) as Preeclampsia_total,
      SUM(caesarean) as caesarean_total,
      SUM(blood_tranf) as blood_tranf_total,
      SUM(women_w_obste_compli) as women_w_obste_compli_total
      ");
        $this->db->from('obstetrical_complication_bc');
        $this->db->where('date_obstetrical_complication_bc', $date);
        return $this->db->get()->row();
    }

    public function surgery($date)
    {
        $this->db->select("
      SUM(appendice_urg) as appendice_urg_total,
      SUM(appendice_plan) as appendice_plan_total,
      SUM(hernioraphy_urg) as hernioraphy_urg_total,
      SUM(hernioraphy_plan) as hernioraphy_plan_total,
      SUM(laparo_urg) as laparo_urg_total,
      SUM(laparo_plan) as laparo_plan_total,
      SUM(tyroide_urg) as tyroide_urg_total,
      SUM(tyroide_plan) as tyroide_plan_total,
      SUM(adeno_urg) as adeno_urg_total,
      SUM(adeno_plan) as adeno_plan_total,
      SUM(gs_other_urg) as gs_other_urg_total,
      SUM(gs_other_plan) as gs_other_plan_total,
      SUM(gs_total) as gs_total_total,
      SUM(cesarean_urg) as cesarean_urg_total,
      SUM(cesarean_plan) as cesarean_plan_total,
      SUM(gyneco_urg) as gyneco_urg_total,
      SUM(gyneco_plan) as gyneco_plan_total,
      SUM(obste_urg) as obste_urg_total,
      SUM(obste_plan) as obste_plan_total,
      SUM(laparo_preg_urg) as laparo_preg_urg_total,
      SUM(laparo_preg_plan) as laparo_preg_plan_total,
      SUM(laparo_rupt_urg) as laparo_rupt_urg_total,
      SUM(laparo_rupt_plan) as laparo_rupt_plan_total,
      SUM(laparo_perit_urg) as laparo_perit_urg_total,
      SUM(laparo_perit_plan) as laparo_perit_plan_total,
      SUM(laparo_myomec_urg) as laparo_myomec_urg_total,
      SUM(laparo_myomec_plan) as laparo_myomec_plan_total,
      SUM(vesico_plan) as vesico_plan_total,
      SUM(recto_plan) as recto_plan_total,
      SUM(ureteric_plan) as ureteric_plan_total,
      SUM(biopsy_plan) as biopsy_plan_total,
      SUM(go_other_urg) as go_other_urg_total,
      SUM(go_other_plan) as go_other_plan_total,
      SUM(go_total) as go_total_total,
      SUM(amputations_urg) as amputations_urg_total,
      SUM(amputations_plan) as amputations_plan_total,
      SUM(osteo_urg) as osteo_urg_total,
      SUM(osteo_plan) as osteo_plan_total,
      SUM(fracture_urg) as fracture_urg_total,
      SUM(fracture_plan) as fracture_plan_total,
      SUM(ortho_other_urg) as ortho_other_urg_total,
      SUM(ortho_other_plan) as ortho_other_plan_total,
      SUM(ortho_total) as ortho_total_total,
      SUM(glaucoma_urg) as glaucoma_urg_total,
      SUM(glaucoma_plan) as glaucoma_plan_total,
      SUM(trachoma_urg) as trachoma_urg_total,
      SUM(trachoma_plan) as trachoma_plan_total,
      SUM(cataract_urg) as cataract_urg_total,
      SUM(cataract_plan) as cataract_plan_total,
      SUM(trauma_plan) as trauma_plan_total,
      SUM(trauma_urg) as trauma_urg_total,
      SUM(oph_other_urg) as oph_other_urg_total,
      SUM(oph_other_plan) as oph_other_plan_total,
      SUM(oph_total) as oph_total_total,
      SUM(cleft_urg) as cleft_urg_total,
      SUM(cleft_plan) as cleft_plan_total,
      SUM(plastic_other_urg) as plastic_other_urg_total,
      SUM(plastic_other_plan) as plastic_other_plan_total,
      SUM(plastic_total) as plastic_total_total,
      SUM(total_urg) as total_urg_total,
      SUM(total_plan) as total_plan_total,
      SUM(major_urg) as major_urg_total,
      SUM(major_plan) as major_plan_total,
      SUM(minor_urg) as minor_urg_total,
      SUM(minor_plan) as minor_plan_total
      ");
        $this->db->from('surgery');
        $this->db->where('date_surgery', $date);
        return $this->db->get()->row();
    }

    public function neonatal($date)
    {
        return $this->db->get_where('neonatal', array('date_neonatal' => $date))->row();
    }

    public function nutrition($date)
    {
        return $this->db->get_where('nutrition_screening', array('date_nutrition_screening' => $date))->row();
    }

    public function malnourished($date)
    {
        return $this->db->get_where('malnourished_rehabilitation', array('date_malnourished_rehabilitation' => $date))->row();
    }

    public function imagery($date)
    {
        return $this->db->get_where('medical_imagery', array('date_medical_imagery' => $date))->row();
    }

    public function stock($date)
    {
        return $this->db->get_where('pharmacy', array('date_pharmacy' => $date))->row();
    }

    public function staff($date)
    {
        return $this->db->get_where('staff', array('date_staff' => $date))->row();
    }
}
