<?php
class XI_M extends CI_Model
{
    public function fetch_data2($a)
    {
      return $this->db->set(array(
      'num_user' => 1, 'service' => $a, 'login' => $a, 'password' => $a
    ))
            ->insert('user');
    }

    public function fetch_data(
      $sexual_violence_5m, $sexual_violence_5f, $sexual_violence_9f, $sexual_violence_9m,
      $sexual_violence_18m, $sexual_violence_18f, $sexual_violence_24m, $sexual_violence_24f,
      $sexual_violence_25f, $sexual_violence_25m,
      $physical_violence_5m, $physical_violence_5f, $physical_violence_9f, $physical_violence_9m,
      $physical_violence_18m, $physical_violence_18f, $physical_violence_24m, $physical_violence_24f,
      $physical_violence_25f, $physical_violence_25m,
      $emotional_violence_5m, $emotional_violence_5f, $emotional_violence_9f, $emotional_violence_9m,
      $emotional_violence_18m, $emotional_violence_18f, $emotional_violence_24m, $emotional_violence_24f,
      $emotional_violence_25f, $emotional_violence_25m,
      $economic_violence_5m, $economic_violence_5f, $economic_violence_9f, $economic_violence_9m,
      $economic_violence_18m, $economic_violence_18f, $economic_violence_24m, $economic_violence_24f,
      $economic_violence_25f, $economic_violence_25m,
      $refered_higher_level_5m, $refered_higher_level_5f, $refered_higher_level_9f, $refered_higher_level_9m,
      $refered_higher_level_18m, $refered_higher_level_18f, $refered_higher_level_24m, $refered_higher_level_24f,
      $refered_higher_level_25f, $refered_higher_level_25m,
      $refered_police_5m, $refered_police_5f, $refered_police_9f, $refered_police_9m,
      $refered_police_18m, $refered_police_18f, $refered_police_24m, $refered_police_24f,
      $refered_police_25f, $refered_police_25m,
      $refered_community_5m, $refered_community_5f, $refered_community_9f, $refered_community_9m,
      $refered_community_18m, $refered_community_18f, $refered_community_24m, $refered_community_24f,
      $refered_community_25f, $refered_community_25m,
      $hiv_5m, $hiv_5f, $hiv_9f, $hiv_9m,
      $hiv_18m, $hiv_18f, $hiv_24m, $hiv_24f,
      $hiv_25f, $hiv_25m,
      $disabilities_5m, $disabilities_5f, $disabilities_9f, $disabilities_9m,
      $disabilities_18m, $disabilities_18f, $disabilities_24m, $disabilities_24f,
      $disabilities_25f, $disabilities_25m,
      $deaths_5m, $deaths_5f, $deaths_9f, $deaths_9m,
      $deaths_18m, $deaths_18f, $deaths_24m, $deaths_24f,
      $deaths_25f, $deaths_25m,
      $pregnant_9f, $pregnant_18f, $pregnant_24f, $pregnant_25f,
      $contraception_9f, $contraception_18f, $contraception_24f, $contraception_25f,
      $exposure_hiv_5m, $exposure_hiv_5f, $exposure_hiv_9f, $exposure_hiv_9m,
      $exposure_hiv_18m, $exposure_hiv_18f, $exposure_hiv_24m, $exposure_hiv_24f,
      $exposure_hiv_25f, $exposure_hiv_25m
    ){
      return $this->db->set(array(
      'sexual_violence_5m' => $sexual_violence_5m,
      'sexual_violence_5f' => $sexual_violence_5f,
      'sexual_violence_9m' => $sexual_violence_9m,
      'sexual_violence_9f' => $sexual_violence_9f,
      'sexual_violence_18m' => $sexual_violence_18m,
      'sexual_violence_18f' => $sexual_violence_18f,
      'sexual_violence_24m' => $sexual_violence_24m,
      'sexual_violence_24f' => $sexual_violence_24f,
      'sexual_violence_25m' => $sexual_violence_25m,
      'sexual_violence_25f' => $sexual_violence_25f,

      'physical_violence_5m' => $physical_violence_5m,
      'physical_violence_5f' => $physical_violence_5f,
      'physical_violence_9m' => $physical_violence_9m,
      'physical_violence_9f' => $physical_violence_9f,
      'physical_violence_18m' => $physical_violence_18m,
      'physical_violence_18f' => $physical_violence_18f,
      'physical_violence_24m' => $physical_violence_24m,
      'physical_violence_24f' => $physical_violence_24f,
      'physical_violence_25m' => $physical_violence_25m,
      'physical_violence_25f' => $physical_violence_25f,

      'emotional_violence_5m' => $emotional_violence_5m,
      'emotional_violence_5f' => $emotional_violence_5f,
      'emotional_violence_9m' => $emotional_violence_9m,
      'emotional_violence_9f' => $emotional_violence_9f,
      'emotional_violence_18m' => $emotional_violence_18m,
      'emotional_violence_18f' => $emotional_violence_18f,
      'emotional_violence_24m' => $emotional_violence_24m,
      'emotional_violence_24f' => $emotional_violence_24f,
      'emotional_violence_25m' => $emotional_violence_25m,
      'emotional_violence_25f' => $emotional_violence_25f,

      'economic_violence_5m' => $economic_violence_5m,
      'economic_violence_5f' => $economic_violence_5f,
      'economic_violence_9m' => $economic_violence_9m,
      'economic_violence_9f' => $economic_violence_9f,
      'economic_violence_18m' => $economic_violence_18m,
      'economic_violence_18f' => $economic_violence_18f,
      'economic_violence_24m' => $economic_violence_24m,
      'economic_violence_24f' => $economic_violence_24f,
      'economic_violence_25m' => $economic_violence_25m,
      'economic_violence_25f' => $economic_violence_25f,

      'refered_higher_level_5m' => $refered_higher_level_5m,
      'refered_higher_level_5f' => $refered_higher_level_5f,
      'refered_higher_level_9m' => $refered_higher_level_9m,
      'refered_higher_level_9f' => $refered_higher_level_9f,
      'refered_higher_level_18m' => $refered_higher_level_18m,
      'refered_higher_level_18f' => $refered_higher_level_18f,
      'refered_higher_level_24m' => $refered_higher_level_24m,
      'refered_higher_level_24f' => $refered_higher_level_24f,
      'refered_higher_level_25m' => $refered_higher_level_25m,
      'refered_higher_level_25f' => $refered_higher_level_25f,

      'refered_police_5m' => $refered_police_5m,
      'refered_police_5f' => $refered_police_5f,
      'refered_police_9m' => $refered_police_9m,
      'refered_police_9f' => $refered_police_9f,
      'refered_police_18m' => $refered_police_18m,
      'refered_police_18f' => $refered_police_18f,
      'refered_police_24m' => $refered_police_24m,
      'refered_police_24f' => $refered_police_24f,
      'refered_police_25m' => $refered_police_25m,
      'refered_police_25f' => $refered_police_25f,

      'refered_community_5m' => $refered_community_5m,
      'refered_community_5f' => $refered_community_5f,
      'refered_community_9m' => $refered_community_9m,
      'refered_community_9f' => $refered_community_9f,
      'refered_community_18m' => $refered_community_18m,
      'refered_community_18f' => $refered_community_18f,
      'refered_community_24m' => $refered_community_24m,
      'refered_community_24f' => $refered_community_24f,
      'refered_community_25m' => $refered_community_25m,
      'refered_community_25f' => $refered_community_25f,

      'hiv_5m' => $hiv_5m,
      'hiv_5f' => $hiv_5f,
      'hiv_9m' => $hiv_9m,
      'hiv_9f' => $hiv_9f,
      'hiv_18m' => $hiv_18m,
      'hiv_18f' => $hiv_18f,
      'hiv_24m' => $hiv_24m,
      'hiv_24f' => $hiv_24f,
      'hiv_25m' => $hiv_25m,
      'hiv_25f' => $hiv_25f,

      'disabilities_5m' => $disabilities_5m,
      'disabilities_5f' => $disabilities_5f,
      'disabilities_9m' => $disabilities_9m,
      'disabilities_9f' => $disabilities_9f,
      'disabilities_18m' => $disabilities_18m,
      'disabilities_18f' => $disabilities_18f,
      'disabilities_24m' => $disabilities_24m,
      'disabilities_24f' => $disabilities_24f,
      'disabilities_25m' => $disabilities_25m,
      'disabilities_25f' => $disabilities_25f,

      'deaths_5m' => $deaths_5m,
      'deaths_5f' => $deaths_5f,
      'deaths_9m' => $deaths_9m,
      'deaths_9f' => $deaths_9f,
      'deaths_18m' => $deaths_18m,
      'deaths_18f' => $deaths_18f,
      'deaths_24m' => $deaths_24m,
      'deaths_24f' => $deaths_24f,
      'deaths_25m' => $deaths_25m,
      'deaths_25f' => $deaths_25f,

      'pregnant_9f' => $pregnant_9f,
      'pregnant_18f' => $pregnant_18f,
      'pregnant_24f' => $pregnant_24f,
      'pregnant_25f' => $pregnant_25f,

      'contraception_9f' => $contraception_9f,
      'contraception_18f' => $contraception_18f,
      'contraception_24f' => $contraception_24f,
      'contraception_25f' => $contraception_25f,

      'exposure_hiv_5m' => $exposure_hiv_5m,
      'exposure_hiv_5f' => $exposure_hiv_5f,
      'exposure_hiv_9m' => $exposure_hiv_9m,
      'exposure_hiv_9f' => $exposure_hiv_9f,
      'exposure_hiv_18m' => $exposure_hiv_18m,
      'exposure_hiv_18f' => $exposure_hiv_18f,
      'exposure_hiv_24m' => $exposure_hiv_24m,
      'exposure_hiv_24f' => $exposure_hiv_24f,
      'exposure_hiv_25m' => $exposure_hiv_25m,
      'exposure_hiv_25f' => $exposure_hiv_25f
    ))
            ->set('date_gender_based_violence', 'NOW()', false)
            ->insert('Gender_Based_Violence');
    }
}
